name: CI

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - run: go get -v -t -d ./...
      - run: go test ./...
      - run: go build -v .
      - run: go vet

  docker-build:
    name: Build Docker image (smoke test)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker build .
